from chart_generation.collect_input import collect_input
from chart_generation.data_collection import collect_data
import chart_generation.dicts
import chart_generation.hundred
import chart_generation.validation_methods as vms